Add example with parameters
Xiphe/cachified pull request #33
Opened 2023-02-06 22:53 UTC by tomanagle

- Adds an example with parameters to show that the key must be unique for each resource
- Adds an extra line of explainer to the key option

2023-02-07 09:43 UTC, Xiphe commented on readme.md
>  ```
I'd get rid of this example in favor of yours

2023-02-07 09:43 UTC, Xiphe commented on readme.md
> +     const response fetch(`https://example.com/users/${userId}`)
theres an `=` missing and indentation is wrong

2023-02-07 09:43 UTC, Xiphe commented on readme.md
> +    return response.json();
please add two more spaces for indentation

2023-02-07 09:45 UTC, Xiphe requested changes
Awesome! Thanks for the contribution and input. I have some minor changes I'd like to see with this. If you want I can also add them, just let me know.

2023-02-07 22:16 UTC, tomanagle commented
Nah, all good. I'll update the PR now. Thanks for the feedback

2023-02-07 22:26 UTC, tomanagle commented
I've updated the PR. I removed the PI example and added the `getUserById` example. I also changed the URL to something that will work, just because people may want to copy it and run it to see t working.

2023-02-08 10:24 UTC, merged

2023-02-08 10:25 UTC, Xiphe commented
awesome! thank you for the contribution 🎉